Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install -y sqlite3 python3-pip zip xlsx2csv 
     pip3 install xlsxwriter openpyxl
  SHELL
end
