Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080 
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
     debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
     debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-user string root"
     debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password it635"
     debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password it635"
     debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password it635"
     apt-get install -y apache2 mysql-server php libapache2-mod-php php-mysql phpmyadmin 
     mysql < /vagrant/setup.sql
  SHELL
end
