= Exercise 7

In this exercise, we will be:

* Installing MongoDB
* Testing the installation
* Downloading the Sakila DVD rental database in JSON format for import into
  MongoDB
* Performing our first query with MongoDB
* Answering a few questions

== Installing MongoDB

MongoDB has packages for most popular operating systems and is broken into separate installers.
Download _MongoDB Community Server_ for your OS https://www.mongodb.com/try/download/community[here] and follow the installation instructions.
A reboot will be required.
Also download and install the https://www.mongodb.com/try/download/database-tools[MongoDB command line tools for your OS].
Be sure to set your Path so you can run the tools, consult the documentation.
Finally install `mongosh` using https://www.mongodb.com/docs/mongodb-shell/install/[these directions].

== Testing our installation

MongoDB should now be running in the background as a service and we should be able to via the mongo shell:

[source, console]
----
PS C:\Users\rxt1077> mongosh
Current Mongosh Log ID: 640a5a7a1e2f6944eebe6e33
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1
.8.0
Using MongoDB:          6.0.4
Using Mongosh:          1.8.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

------
   The server generated these startup warnings when booting
   2023-03-09T15:04:09.754-05:00: Access control is not enabled for the database. Read and write access to data and conf
iguration is unrestricted
------

------
   Enable MongoDB's free cloud-based monitoring service, which will then receive and display
   metrics about your deployment (disk utilization, CPU, operation statistics, etc).

   The monitoring data will be available on a MongoDB website with a unique URL accessible to you
   and anyone you share the URL with. MongoDB may use this information to make product
   improvements and to suggest MongoDB products and deployment options to you.

   To enable free monitoring, run the following command: db.enableFreeMonitoring()
   To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
------

test> show dbs
admin   40.00 KiB
config  12.00 KiB
local   72.00 KiB
test> exit
----

== Downloading and loading the Sample DB

We will be using the Sakila database, converted to JSON which can be found in three files https://github.com/rxt1077/IT635/tree/master/sakila-json[here].

[source, console]
----
PS C:\Users\rxt1077\it635\sakila-json> mongoimport customers.json
2023-03-09T17:21:24.430-0500    no collection specified
2023-03-09T17:21:24.431-0500    using filename 'customers' as collection
2023-03-09T17:21:24.443-0500    connected to: mongodb://localhost/
2023-03-09T17:21:24.566-0500    599 document(s) imported successfully. 0 document(s) failed to import.
PS C:\Users\rxt1077\it635\sakila-json> mongoimport films.json  
2023-03-09T17:21:33.528-0500    no collection specified
2023-03-09T17:21:33.529-0500    using filename 'films' as collection
2023-03-09T17:21:33.539-0500    connected to: mongodb://localhost/
2023-03-09T17:21:33.574-0500    1000 document(s) imported successfully. 0 document(s) failed to import.
PS C:\Users\rxt1077\it635\sakila-json> mongoimport stores.json   
2023-03-09T17:23:05.374-0500    no collection specified
2023-03-09T17:23:05.375-0500    using filename 'stores' as collection
2023-03-09T17:23:05.386-0500    connected to: mongodb://localhost/
2023-03-09T17:23:05.409-0500    2 document(s) imported successfully. 0 document(s) failed to import.
----

== Performing a query

Now let's connect to the MongoDB and find the object in the `film` collection named `ALI FOREVER`:

[source, console]
----
PS C:\Users\rxt1077\it635\sakila-json> mongosh
Current Mongosh Log ID: 640a5c6fdc1a1a117b00a5d2
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1
.8.0
Using MongoDB:          6.0.4
Using Mongosh:          1.8.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

------
   The server generated these startup warnings when booting
   2023-03-09T15:04:09.754-05:00: Access control is not enabled for the database. Read and write access to data and conf
iguration is unrestricted
------

------
   Enable MongoDB's free cloud-based monitoring service, which will then receive and display
   metrics about your deployment (disk utilization, CPU, operation statistics, etc).

   The monitoring data will be available on a MongoDB website with a unique URL accessible to you
   and anyone you share the URL with. MongoDB may use this information to make product
   improvements and to suggest MongoDB products and deployment options to you.

   To enable free monitoring, run the following command: db.enableFreeMonitoring()
   To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
------

test> show collections
customers
films
stores
test> db.films.find( { Title: "ALI FOREVER" } )
[
  {
    _id: 13,
    Actors: [
      { 'First name': 'CARY', 'Last name': 'MCCONAUGHEY', actorId: 77 },
      {
        'First name': 'CHRISTOPHER',
        'Last name': 'BERRY',
        actorId: 91
      },
      { 'First name': 'KENNETH', 'Last name': 'TORN', actorId: 94 },
      {
        'First name': 'MORGAN',
        'Last name': 'MCDORMAND',
        actorId: 114
      },
      { 'First name': 'JON', 'Last name': 'CHASE', actorId: 176 }
    ],
    Category: 'Horror',
    Description: 'A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies'
,
    Length: '150',
    Rating: 'PG',
    'Rental Duration': '4',
    'Replacement Cost': '21.99',
    'Special Features': 'Deleted Scenes,Behind the Scenes',
    Title: 'ALI FOREVER'
  }
]
test> quit
----

MongoDB queries consist of multiple documents (parameters) passed as JSON. The
first document (the only one we are using today) is called the
https://docs.mongodb.com/manual/core/document/#document-query-filter[query
filter document]. Ours is `{ Title: "ALI FOREVER" }` meaning we want to
documents that match the title `ALI FOREVER`. You can learn more about
https://docs.mongodb.com/manual/tutorial/query-documents/[MongoDB queries here].

== Questions

Please use the text box for this assignment to answer the following questions:

. Why might JSON be easier for developers to use than SQL?
. Why does the film we queried have an `_id` attribute even though it wasn't in
  the original data?
. Based on today's query, collections in MongoDB seem analogous to what in
  PostgreSQL?
