version: '3.1'
services:
    db1:
        image: mongo
        command: --replSet "rs0"
        volumes:
            - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    db2:
        image: mongo
        command: --replSet "rs0"
    db3:
        image: mongo
        command: --replSet "rs0"
