Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        # Make master and slave point to our IPs
        echo "192.168.1.10 master" >> /etc/hosts
        echo "192.168.1.20 slave" >> /etc/hosts

        # Install mariadb
        apt-get update -y
        apt-get install -y mariadb-server

        # Configure mariadb to listen on all interfaces
        sed -i 's/\\(bind-address.*\\)/#\\1/' /etc/mysql/mariadb.conf.d/50-server.cnf
        cat /etc/mysql/mariadb.conf.d/50-server.cnf | grep bind-address
        systemctl restart mariadb
    SHELL

    config.vm.define "master" do |master|
        master.vm.box = "ubuntu/bionic64"
        master.vm.network "private_network", ip: "192.168.1.10"
        master.vm.provision "shell", inline: <<-SHELL
            # Import our data
            cd /tmp
            tar zxvf /vagrant/sakila-db.tar.gz
            mysql < sakila-db/sakila-schema.sql
            mysql < sakila-db/sakila-data.sql


            # Set ourselves up as a replication master
            echo "[mariadb]" >> /etc/mysql/mariadb.cnf
            echo "log-bin" >> /etc/mysql/mariadb.cnf
            echo "server_id=1" >> /etc/mysql/mariadb.cnf
            echo "log-basename=master" >> /etc/mysql/mariadb.cnf
            systemctl restart mariadb

            # Add the replication user
            mysql < /vagrant/setup_replication_user.sql
        SHELL
    end

    config.vm.define "slave" do |slave|
        slave.vm.box = "ubuntu/bionic64"
        slave.vm.network "private_network", ip: "192.168.1.20"
    end
end
